services:
  - type: web
    name: evolution-api
    runtime: docker
    # Add these two lines to point to your folder
    dockerContext: evolution-api
    dockerfilePath: evolution-api/Dockerfile
    envVars:
      - key: AUTHENTICATION_API_KEY
        sync: false 
      - key: DATABASE_ENABLED
        value: "true"
      - key: DATABASE_CONNECTION_URI
        fromDatabase:
          name: evolution-db
          property: connectionString
      - key: CACHE_REDIS_ENABLED
        value: "true"
      - key: CACHE_REDIS_URI
        value: redis://evolution-redis:6379

  - type: redis
    name: evolution-redis
    plan: free
    ipAllowList: []

databases:
  - name: evolution-db
    plan: free