services:
  - type: web
    name: evolution-api
    runtime: docker
    plan: free
    envVars:
      - key: AUTHENTICATION_API_KEY
        sync: false # Prompts you for the key during deploy
      - key: DATABASE_ENABLED
        value: "true"
      - key: DATABASE_CONNECTION_URI
        fromDatabase:
          name: evolution-db
          property: connectionString
      - key: CACHE_REDIS_ENABLED
        value: "true"
      - key: CACHE_REDIS_URI
        fromRedis: 
          name: evolution-redis
          property: connectionString

databases:
  - name: evolution-db
    plan: free

redis: 
  - name: evolution-redis
    plan: free